const Data = [
    {
        imgsrc: "https://i.picsum.photos/id/659/2731/1536.jpg?hmac=jwFueQ8WaCS2sR6LVKFGQ3-emm0_HqHEOhQDt8AzHyQ",
        title: "This is Dog",
        location: "location:Zurich Forest",
        country: "Switzerland",
        sname: "Pet Name:Tom",
        color: "color:Black",
        type:"type:Animal",
        category:"order:Omnivore",
        family:"family:Canidae",
        link: "https://i.picsum.photos/id/659/2731/1536.jpg?hmac=jwFueQ8WaCS2sR6LVKFGQ3-emm0_HqHEOhQDt8AzHyQ", 
    },
    {
        imgsrc: "https://i.picsum.photos/id/1003/1181/1772.jpg?hmac=oN9fHMXiqe9Zq2RM6XT-RVZkojgPnECWwyEF1RvvTZk",
        title: "This is Deer ",
        location:"location:Himalayas",
        country: "India",
        sname: "Pet Name:Geno",
        color: "color:Brown",
        type:"type:Animal",
        category:"order:Herbivores",
        family:"family:Cervidae",
        link: "https://i.picsum.photos/id/1003/1181/1772.jpg?hmac=oN9fHMXiqe9Zq2RM6XT-RVZkojgPnECWwyEF1RvvTZk",
    },
    {
        imgsrc: "https://i.picsum.photos/id/237/3500/2095.jpg?hmac=y2n_cflHFKpQwLOL1SSCtVDqL8NmOnBzEW7LYKZ-z_o",
        title: "This is Dog",
        location: "location:London",
        country: "England",
        sname: "Pet Name:Daisy",
        color: "color:Black",
        type:"type:Animal",
        category:"order:Omnivore",
        family:"family:Canidae",
        link:  "https://i.picsum.photos/id/237/3500/2095.jpg?hmac=y2n_cflHFKpQwLOL1SSCtVDqL8NmOnBzEW7LYKZ-z_o",
    },
    {
        imgsrc: "https://i.picsum.photos/id/582/2509/1673.jpg?hmac=KYDKBZqFQyCEgf4p4LrOXyyiI1J_0Hf77_MO-vWEdCw",
        title: "This is Fox",
        location: "location:National Forest",
        country: "Iceland",
        sname: "Pet Name:Buddy",
        color: "color:Brown",
        type:"type:Animal",
        category:"order:Omnivore",
        family:"family:Canidae",
        link: "https://i.picsum.photos/id/582/2509/1673.jpg?hmac=KYDKBZqFQyCEgf4p4LrOXyyiI1J_0Hf77_MO-vWEdCw",
    },
    {
        imgsrc: "https://i.picsum.photos/id/1024/1920/1280.jpg?hmac=-PIpG7j_fRwN8Qtfnsc3M8-kC3yb0XYOBfVzlPSuVII",
        title: "This is Eagle",
        location: "location:Aner Dam",
        country: "India",
        sname: "Pet Name:Pilot",
        color: "color:Brown",
        type:"type:Bird",
        category:"order:Carnivore",
        family:"family:Accipitridae",
        link: "https://i.picsum.photos/id/1024/1920/1280.jpg?hmac=-PIpG7j_fRwN8Qtfnsc3M8-kC3yb0XYOBfVzlPSuVII",
    },
    {
        imgsrc: "https://i.picsum.photos/id/1074/5472/3648.jpg?hmac=w-Fbv9bl0KpEUgZugbsiGk3Y2-LGAuiLZOYsRk0zo4A",
        title: "This is Tiger",
        location:"location:Tadoba Andheri Tiger Reserve",
        country: "India",
        sname: "Pet Name:King",
        color: "color:Dark Brown",
        type:"type:Animal",
        category:"order:Carnivore",
        family:"family:Felidae",
        link: "https://i.picsum.photos/id/1074/5472/3648.jpg?hmac=w-Fbv9bl0KpEUgZugbsiGk3Y2-LGAuiLZOYsRk0zo4A",
    },
    {
        imgsrc: "https://i.picsum.photos/id/1084/4579/3271.jpg?hmac=YblMazviSugJVfZsFPaFI_Vp6lBeQin62qpm8rxHruo",
        title: "This is Sealion",
        location:"location:Orkney Islands",
        country: "Scotland",
        sname: "Pet Name:Snoofy",
        color: "color:Brown",
        type:"type:Animal",
        category:"order:Carnivore",
        family:"family:Otariidae",
        link:  "https://i.picsum.photos/id/1084/4579/3271.jpg?hmac=YblMazviSugJVfZsFPaFI_Vp6lBeQin62qpm8rxHruo",
    },
    {
        imgsrc: "https://i.picsum.photos/id/219/5184/3456.jpg?hmac=2LU7i3c6fykd_J0T6rZm1aBoBmK4ivkH1Oc459aRUU0",
        title: "This is Cheetah",
        location:"location:Sahara Dessert",
        country: "Morocco",
        sname: "Pet Name:Bruno",
        color: "color:Black,Brown",
        type:"type:Animal",
        category:"order:Carnivore",
        family:"family:Felidae",
        link:  "https://i.picsum.photos/id/219/5184/3456.jpg?hmac=2LU7i3c6fykd_J0T6rZm1aBoBmK4ivkH1Oc459aRUU0",
    },
    {
        imgsrc: "https://i.picsum.photos/id/244/4288/2848.jpg?hmac=R6j9PBP4aBk2vcEIoOPU4R_nuknizryn2Vq8GGtWTrM",
        title: "This is Black Skimmer",
        location:"location:Karnala Sanctuary",
        country: "India",
        sname: "Pet Name:Rusty",
        color: "color:Grey",
        type:"type:Bird",
        category:"order:Omnivore",
        family:"family:Laridae",
        link: "https://i.picsum.photos/id/244/4288/2848.jpg?hmac=R6j9PBP4aBk2vcEIoOPU4R_nuknizryn2Vq8GGtWTrM",
    },
    {
        imgsrc: "https://i.picsum.photos/id/433/4752/3168.jpg?hmac=Og-twcmaH_j-JNExl5FsJk1pFA7o3-F0qeOblQiJm4s",
        title: "This is Bear",
        location:"location:Siberian Forests",
        country: "Russsia",
        sname: "Pet Name:Ted",
        color: "color:Brown",
        type:"type:Animal",
        category:"order:Omnivore",
        family:"family:Ursidae",
        link:  "https://i.picsum.photos/id/433/4752/3168.jpg?hmac=Og-twcmaH_j-JNExl5FsJk1pFA7o3-F0qeOblQiJm4s",
    },
];

export default Data;
